# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#
# Site settings
#
title: Vinilificio
email: info@vinilificio.com
description: > # this means to ignore newlines until "baseurl:"
  Since 2005 Vinilificio produces vinyl records in single copy, small runs and quantities!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.vinilificio.com" # the base hostname & protocol for your site
app_link: "https://app.vinilificio.com"

#
# Build settings
#

# Include
include: ["_pages"]

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# Defaults
defaults:
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "default"
      position: "footer"
      index: 1
      permalink: /:basename/
  -
    scope:
      path: "en"
      type: "pages"
    values:
      layout: "default"
      position: "footer"
      index: 1
      permalink: /:path/:basename/

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :compressed # You might prefer to minify using :compressed

# Locales
locales:
  it:
    description: "Dal 2005 Vinilificio produce vinili in singola copia, piccole tirature oppure stampe in quantità!"
    make_vinyl: "Crea il tuo vinile"
    info: "Informazioni"

  en:
    description: "Since 2005 Vinilificio produces vinyl records in single copy, small runs and quantities!"
    make_vinyl: "Make your vinyl"
    info: "Information"