version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - run:
          name: install dependencies
          command: bundle install
      - run:
          name: build site
          command: bundle exec jekyll build
      - persist_to_workspace:
          root: '.'
          paths:
            - _site
  deploy:
    docker:
      - image: circleci/python:3.4
    steps:
      - run:
          name: install AWS CLI
          command: pip install awscli
      - attach_workspace:
          at: '.'
      - deploy:
          name: deploy on S3
          command: aws s3 sync _site s3://$CNAME --region ${AWS_REGION:-eu-west-1} --delete --dryrun
      - deploy:
          name: create CloudFront invalidation
          command: aws cloudfront create-invalidation --paths '/*' --distribution-id $(aws cloudfront list-distributions --query "DistributionList.Items[?contains(Aliases.Items, '${CNAME}')].Id" --output text)

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          context: staging
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
          context: production

